version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"

  web:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend