name: Python Code Quality Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8

    - name: Run black
      run: |
        black --check ./backend

    - name: Run flake8
      run: |
        flake8 ./backend